apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "python-app.fullname" . }}
  labels:
{{ include "python-app.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "python-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
{{ include "python-app.labels" . | indent 8 }}
    spec:
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
{{- end }}
      containers:
        - name: {{ include "python-app.name" . }}
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
    {{- if .Values.nodeSelector }}
      nodeSelector:
    {{ toYaml .Values.nodeSelector | indent 6 }}
    {{- else }}
      nodeSelector: {}
    {{- end }}

    {{- if .Values.tolerations }}
      tolerations:
    {{ toYaml .Values.tolerations | indent 6 }}
    {{- else }}
      tolerations: []
    {{- end }}

    {{- if .Values.affinity }}
      affinity:
    {{ toYaml .Values.affinity | indent 6 }}
    {{- else }}
      affinity: {}
    {{- end }}
