apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "python-app.fullname" . }}
  labels:
    {{ include "python-app.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "python-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{ include "python-app.labels" . | indent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "python-app.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 6 }}
      tolerations: {{- toYaml .Values.tolerations | nindent 6 }}
      affinity: {{- toYaml .Values.affinity | nindent 6 }}
